# Generated by Django 4.2.1 on 2023-08-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredusers',
            name='username',
        ),
    ]
