# Generated by Django 4.2.1 on 2023-08-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_remove_registeredusers_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='UrlMapper',
        ),
    ]
